<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
	version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:sm="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
	exclude-result-prefixes="sm image">

	<xsl:output method="html" encoding="UTF-8" indent="yes" doctype-system="about:legacy-compat"/>

	<!-- ================================================================
	     Root template — handles both sitemapindex and urlset documents
	     ================================================================ -->
	<xsl:template match="/">
		<html lang="en">
			<head>
				<meta charset="UTF-8"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<title>XML Sitemap &#x2014; MM SEO</title>
				<style><![CDATA[
/* MM SEO Sitemap Stylesheet */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
	font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, sans-serif;
	font-size: 14px;
	line-height: 1.6;
	color: #333;
	background: #f8f9fa;
}

header {
	background: #1d2327;
	color: #fff;
	padding: 20px 32px;
	display: flex;
	align-items: center;
	gap: 16px;
}

header h1 {
	font-size: 20px;
	font-weight: 600;
}

header .badge {
	background: #2271b1;
	color: #fff;
	font-size: 11px;
	font-weight: 600;
	padding: 2px 8px;
	border-radius: 3px;
	letter-spacing: 0.05em;
	text-transform: uppercase;
}

.container {
	max-width: 1100px;
	margin: 32px auto;
	padding: 0 24px;
}

.notice {
	background: #fff;
	border: 1px solid #ddd;
	border-left: 4px solid #2271b1;
	border-radius: 4px;
	padding: 14px 18px;
	margin-bottom: 24px;
	font-size: 13px;
	color: #50575e;
}

.notice strong { color: #1d2327; }

table {
	width: 100%;
	border-collapse: collapse;
	background: #fff;
	border: 1px solid #ddd;
	border-radius: 4px;
	overflow: hidden;
	box-shadow: 0 1px 3px rgba(0,0,0,.06);
}

thead tr {
	background: #f0f0f1;
	border-bottom: 2px solid #c3c4c7;
}

th {
	padding: 12px 16px;
	text-align: left;
	font-size: 12px;
	font-weight: 600;
	color: #50575e;
	text-transform: uppercase;
	letter-spacing: 0.04em;
	white-space: nowrap;
}

td {
	padding: 11px 16px;
	border-bottom: 1px solid #f0f0f1;
	vertical-align: middle;
}

tr:last-child td { border-bottom: none; }

tbody tr:hover { background: #f9f9f9; }

td a {
	color: #2271b1;
	text-decoration: none;
	word-break: break-all;
}

td a:hover { text-decoration: underline; color: #135e96; }

.col-lastmod {
	white-space: nowrap;
	color: #757575;
	font-size: 12px;
}

.col-count {
	text-align: center;
	color: #757575;
	font-size: 12px;
}

.empty { color: #bbb; font-style: italic; }

footer {
	text-align: center;
	padding: 24px;
	font-size: 12px;
	color: #aaa;
}

footer a { color: #888; text-decoration: none; }
footer a:hover { text-decoration: underline; }
				]]></style>
			</head>
			<body>
				<header>
					<h1>XML Sitemap</h1>
					<span class="badge">MM SEO</span>
				</header>
				<div class="container">
					<xsl:choose>
						<xsl:when test="sm:sitemapindex">
							<xsl:apply-templates select="sm:sitemapindex"/>
						</xsl:when>
						<xsl:when test="sm:urlset">
							<xsl:apply-templates select="sm:urlset"/>
						</xsl:when>
						<xsl:otherwise>
							<p class="empty">No sitemap data found.</p>
						</xsl:otherwise>
					</xsl:choose>
				</div>
				<footer>
					<p>Generated by <a href="https://martinimultimedia.com" rel="noopener">MM SEO by Martini Multimedia</a></p>
				</footer>
			</body>
		</html>
	</xsl:template>

	<!-- ================================================================
	     Sitemap Index
	     ================================================================ -->
	<xsl:template match="sm:sitemapindex">
		<div class="notice">
			<strong>Sitemap Index</strong> &#x2014;
			This index contains <strong><xsl:value-of select="count(sm:sitemap)"/></strong>
			<xsl:choose>
				<xsl:when test="count(sm:sitemap) = 1"> sitemap.</xsl:when>
				<xsl:otherwise> sitemaps.</xsl:otherwise>
			</xsl:choose>
			Search engines use this file to discover all URLs on your site.
		</div>
		<table>
			<thead>
				<tr>
					<th>Sitemap URL</th>
					<th class="col-lastmod">Last Modified</th>
				</tr>
			</thead>
			<tbody>
				<xsl:apply-templates select="sm:sitemap"/>
			</tbody>
		</table>
	</xsl:template>

	<xsl:template match="sm:sitemap">
		<tr>
			<td>
				<a href="{sm:loc}">
					<xsl:value-of select="sm:loc"/>
				</a>
			</td>
			<td class="col-lastmod">
				<xsl:choose>
					<xsl:when test="sm:lastmod">
						<xsl:value-of select="substring(sm:lastmod, 1, 10)"/>
					</xsl:when>
					<xsl:otherwise>
						<span class="empty">&#x2014;</span>
					</xsl:otherwise>
				</xsl:choose>
			</td>
		</tr>
	</xsl:template>

	<!-- ================================================================
	     URL Set
	     ================================================================ -->
	<xsl:template match="sm:urlset">
		<div class="notice">
			<strong>URL Sitemap</strong> &#x2014;
			This sitemap contains <strong><xsl:value-of select="count(sm:url)"/></strong>
			<xsl:choose>
				<xsl:when test="count(sm:url) = 1"> URL.</xsl:when>
				<xsl:otherwise> URLs.</xsl:otherwise>
			</xsl:choose>
		</div>
		<table>
			<thead>
				<tr>
					<th>URL</th>
					<th class="col-lastmod">Last Modified</th>
					<th class="col-count">Images</th>
				</tr>
			</thead>
			<tbody>
				<xsl:apply-templates select="sm:url"/>
			</tbody>
		</table>
	</xsl:template>

	<xsl:template match="sm:url">
		<tr>
			<td>
				<a href="{sm:loc}">
					<xsl:value-of select="sm:loc"/>
				</a>
			</td>
			<td class="col-lastmod">
				<xsl:choose>
					<xsl:when test="sm:lastmod">
						<xsl:value-of select="substring(sm:lastmod, 1, 10)"/>
					</xsl:when>
					<xsl:otherwise>
						<span class="empty">&#x2014;</span>
					</xsl:otherwise>
				</xsl:choose>
			</td>
			<td class="col-count">
				<xsl:choose>
					<xsl:when test="image:image">
						<xsl:value-of select="count(image:image)"/>
					</xsl:when>
					<xsl:otherwise>
						<span class="empty">0</span>
					</xsl:otherwise>
				</xsl:choose>
			</td>
		</tr>
	</xsl:template>

</xsl:stylesheet>
