<?php
namespace MMSEO\Modules;

defined( 'ABSPATH' ) || exit;

/**
 * Robots.txt editor module.
 *
 * Prepends custom rules (stored in mmseo_robots_txt option) to WordPress's
 * virtual robots.txt output.
 *
 * If a physical robots.txt exists at ABSPATH, WordPress never fires the
 * robots_txt filter at all, so this module's filter registration is harmless
 * in that case (it simply won't fire). The settings page should warn the admin.
 */
class RobotsTxt extends Module {

	public function id(): string {
		return 'robots_editor';
	}

	public function register(): void {
		add_filter( 'robots_txt', [ $this, 'prepend_custom_rules' ], 10, 2 );
	}

	// -------------------------------------------------------------------------
	// Filter callback
	// -------------------------------------------------------------------------

	/**
	 * Prepend custom robots.txt rules before WordPress's generated output.
	 *
	 * @param string $output  The robots.txt output generated by WordPress.
	 * @param bool   $public  Whether the site is set to public (discouraging search engines = false).
	 * @return string
	 */
	public function prepend_custom_rules( string $output, bool $public ): string {
		$custom = trim( (string) get_option( 'mmseo_robots_txt', '' ) );

		if ( '' === $custom ) {
			return $output;
		}

		// Put custom block first, then the standard WP-generated content.
		return $custom . "\n\n" . $output;
	}
}
